# Generated by Django 2.2 on 2019-05-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190518_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='techer',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
