# Generated by Django 2.2 on 2019-05-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_techer_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Techer',
            new_name='Teacher',
        ),
    ]
