# Generated by Django 2.2 on 2019-05-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20190524_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '讲师', 'verbose_name_plural': '讲师'},
        ),
    ]
