# Generated by Django 2.2 on 2019-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='课程类别'),
        ),
    ]
