# Generated by Django 2.2 on 2019-06-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20190526_1038'),
        ('courses', '0006_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='organization.Teacher', verbose_name='讲师'),
        ),
    ]
