# Generated by Django 2.2 on 2019-07-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190725_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='detail',
            field=models.TextField(verbose_name='课程详情'),
        ),
    ]
